language: python
python:
  - 2.7
before_install:
  - sudo apt-get install -y wamerican
install:
  - pip install -e .[test]
  - pip install -e extras/example/client
  - pip install -e extras/example/service
  - pip install coveralls
script:
  - "./extras/example/setup.sh -U postgres"
  - py.test test.py --cov=flask_hype --cov-report term-missing
services:
  - redis-server
addons:
  postgresql: "9.3"
after_success:
  - coveralls
deploy:
  provider: pypi
  user: somepie
  password:
    secure: f01cUCmCqzNyQ2cQcY5sNQPKXlBgESqp7LMohTfZxyugGxdyGV2YgHLH/BJc31JH4Fnq7WBa7Kjo94c2BofY2jTkQMqdMBXXKLbdg5Rwn4imlvFzv1VYJB8Cwl7aTCIIHn5UldKTnJPzt47rn9DI17iPbqCIdOZ5nKt/fO6ltC0=
  on:
    all_branches: true
    tags: true
